---
title: "Tidyverse (New)"
output: 
  learnr::tutorial
runtime: shiny_prerendered
---

```{r context = "setup", include=FALSE, message=FALSE}
library(tidyverse)
library(learnr)
library(shinyjs)

# Tutorial options
options(tutorial.storage = "none")
knitr::opts_chunk$set(echo = FALSE, message = FALSE)

x <- read_csv("test.csv")

# Create initial responses df
responses <- data.frame("", "", "", "", "", "")
names(responses) <- c("time", "user_id", "email", "event", "tutorial_id", "chunk_label",)

# Create event recorder, modified from Kaplan's markr package
test_event_recorder <- function(tutorial_id,
                                user_id,
                                tutorial_version,
                                event, data) {
  this_event <-
    data.frame(time = date(),
               user_id = user_id,
               email = "",
               event = event,
               tutorial_id = tutorial_id,
               chunk_label = ifelse(is.null(data$label), "", data$label),
               stringsAsFactors = FALSE)

  # Don't store the output of chunks -- it can be arbitrarily long.
  if  ( ! event %in% c("exercise_result")) {
    event_df <- data.frame(this_event)
    names(event_df)<- names(responses)
    responses <<- rbind(responses, event_df)
  }
    
}

#  set up the event handler
options(tutorial.event_recorder = test_event_recorder)

```


Load the gapminder library: 

```{r exercise-1, exercise=TRUE}


```

```{r exercise-1-solution}
library(gapminder)
```

Question 2: Glimpse gapminder.

```{r exercise-2, exercise=TRUE}


```

```{r exercise-2-solution}
glimpse(gapminder)

```

```{r context="setup"}

fluidPage(
    shinyjs::useShinyjs(),
    mainPanel(
      title = "Submit form", id = "submitTab", value = "submitTab",
          br(),
          div(id = "form",
            textInput("name", "Name", ""),
            textInput("email", "Harvard Email"),
            actionButton("submit", "Submit", class = "btn-primary"),
            downloadButton("downloadData", "Download")
          )
        )
    )


```


```{r context="server"}

 observeEvent(input$submit,{
        
        responses$user_id <<- input$name
        responses$email <<- input$email
 })

output$downloadData <- downloadHandler(
  
      filename = "responses.csv",
      content = function(file) {
      write_csv(responses, file)
    }
  )



```

